//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpWorkWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppliedJobSeeker
    {
        public int Id { get; set; }
        public Nullable<int> JobSeekerId { get; set; }
        public Nullable<int> PostJobId { get; set; }
        public string YourSay { get; set; }
    
        public virtual JobSeeker JobSeeker { get; set; }
        public virtual PostJob PostJob { get; set; }
    }
}
