//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpWorkWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.JobSeekers = new HashSet<JobSeeker>();
        }
    
        public int Id { get; set; }
        public Nullable<int> JobSeekerCategoryId { get; set; }
        public string HouseTutorClassPlay_5 { get; set; }
        public string HouseTutorClass6_8 { get; set; }
        public string HouseTutorClass9_10 { get; set; }
        public string HouseTutorClass11_12 { get; set; }
        public string HouseTutorPhysics { get; set; }
        public string HouseTutorMath { get; set; }
        public string HouseTutorChemistry { get; set; }
        public string HouseTutorBangla { get; set; }
        public string HouseTutorEnglish { get; set; }
        public string HouseTutorICT { get; set; }
        public string HouseTutorAccounting { get; set; }
        public string DataEntryBasicLevel { get; set; }
        public string DataEntrySecondaryLevel { get; set; }
        public string DataEntryHigherLevel { get; set; }
        public string EventManagerCorporateMeeting { get; set; }
        public string EventManagerFamilyMeeting { get; set; }
        public string EventManagerParty { get; set; }
        public string PhotographyPortrait { get; set; }
        public string PhotographyParty { get; set; }
        public string PhotographyFamily { get; set; }
        public string PhotographyInstitution { get; set; }
        public string GraphicsDesignPhotoshop { get; set; }
        public string GraphicsDesignIllustrator { get; set; }
        public string TransporterBothWay { get; set; }
        public string TransporterOneWay { get; set; }
        public string AdditionalDirectorFilm { get; set; }
        public string AdditionalDirectorShortFilm { get; set; }
        public string AdditionalDirectorDocumentary { get; set; }
        public string ConsultantBusinessTransformation { get; set; }
        public string ConsultantEngineeringConsultants { get; set; }
        public string ConsultantEducationalConsultants { get; set; }
        public string ConsultantHumanResourcesConsultants { get; set; }
        public string ConsultantImmigrationConsultants { get; set; }
        public string ConsultantInternetConsultants { get; set; }
        public string ConsultantInformation_TechnologyConsultants { get; set; }
        public string ConsultantInterimManagers { get; set; }
        public string ConsultantMarketingConsultants { get; set; }
        public string ConsultantProcessConsultants { get; set; }
        public string ConsultantPublic_relationsConsultants { get; set; }
        public string ConsultantPerformanceConsultants { get; set; }
        public string ConsultantSalesConsultants { get; set; }
        public string ConsultantStrategyConsultants { get; set; }
        public string Consultant3DConsultants { get; set; }
        public string WebDesignStatic { get; set; }
        public string WebDesignDynamic { get; set; }
    
        public virtual JobSeeker JobSeeker { get; set; }
        public virtual ICollection<JobSeeker> JobSeekers { get; set; }
    }
}
