//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpWorkWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobProviderPersonal
    {
        public JobProviderPersonal()
        {
            this.PostJobs = new HashSet<PostJob>();
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string NID { get; set; }
        public string PassportNumber { get; set; }
        public string BirthDate { get; set; }
        public string RegDate { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public string Nationnality { get; set; }
        public string Picture { get; set; }
        public string JobProviderCode { get; set; }
        public string Location { get; set; }
        public string Type { get; set; }
        public string PaymentProcedure { get; set; }
        public string Rate { get; set; }
    
        public virtual ICollection<PostJob> PostJobs { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
