//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpWorkWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobProviderCompany
    {
        public JobProviderCompany()
        {
            this.PostJobs = new HashSet<PostJob>();
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string CompanyEmail { get; set; }
        public string Password { get; set; }
        public string RegistrationNumber { get; set; }
        public string Phone { get; set; }
        public string Location { get; set; }
        public string CompanyCode { get; set; }
        public string RegistrationCopy { get; set; }
        public string CompanyWebsite { get; set; }
        public string RegDate { get; set; }
        public string CompanyLogo { get; set; }
        public string Country { get; set; }
        public string Type { get; set; }
        public string PaymentProcedure { get; set; }
        public string Rate { get; set; }
    
        public virtual ICollection<PostJob> PostJobs { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
