//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpWorkWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeeker
    {
        public JobSeeker()
        {
            this.AppliedJobSeekers = new HashSet<AppliedJobSeeker>();
            this.SelectedJobSeekers = new HashSet<SelectedJobSeeker>();
            this.CompleteJobs = new HashSet<CompleteJob>();
            this.Notifications = new HashSet<Notification>();
            this.Messages = new HashSet<Message>();
            this.Categories = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public string Full_Name { get; set; }
        public string Email { get; set; }
        public string Birthdate { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public string Nationnality { get; set; }
        public string Picture { get; set; }
        public string Category { get; set; }
        public string CommentBox { get; set; }
        public string JobSeekerCode { get; set; }
        public string RegDate { get; set; }
        public string Password { get; set; }
        public Nullable<int> CategoryTryId { get; set; }
        public string AvailableStart { get; set; }
        public string AvailableEnd { get; set; }
        public string Location { get; set; }
        public string Type { get; set; }
        public string PaymentProcedure { get; set; }
        public string Rate { get; set; }
    
        public virtual ICollection<AppliedJobSeeker> AppliedJobSeekers { get; set; }
        public virtual ICollection<SelectedJobSeeker> SelectedJobSeekers { get; set; }
        public virtual ICollection<CompleteJob> CompleteJobs { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual Category Category1 { get; set; }
    }
}
