//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpWorkWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public Nullable<int> JobSeekerNotificationId { get; set; }
        public Nullable<int> PostJobNotificationId { get; set; }
        public string Comments { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
    
        public virtual JobSeeker JobSeeker { get; set; }
        public virtual PostJob PostJob { get; set; }
    }
}
