//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpWorkWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UpWorkDBEntities : DbContext
    {
        public UpWorkDBEntities()
            : base("name=UpWorkDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JobSeeker> JobSeekers { get; set; }
        public virtual DbSet<JobProviderPersonal> JobProviderPersonals { get; set; }
        public virtual DbSet<JobProviderCompany> JobProviderCompanies { get; set; }
        public virtual DbSet<PostJob> PostJobs { get; set; }
        public virtual DbSet<AppliedJobSeeker> AppliedJobSeekers { get; set; }
        public virtual DbSet<SelectedJobSeeker> SelectedJobSeekers { get; set; }
        public virtual DbSet<CompleteJob> CompleteJobs { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
    }
}
